version: '3.5'
services:
  prusa:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - /opt/op/prusa:/octoprint
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - ENABLE_MJPG_STREAMER=false
    ports:
      - 8082:5000
  
  artillery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - /dev:/dev
      - /opt/op/artillery:/octoprint
    devices:
      - /dev/ttyACM1:/dev/tty/ACM1
    environment:
      - ENABLE_MJPG_STREAMER=false
    ports:
      - 8081:5000

