version: '3.5'
services:
  prusa:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: on-failure
    volumes:
      - /dev:/dev
      - /opt/op/prusa:/octoprint
      - /opt/op/plugins:/octoprint/vendor
    devices:
      - /dev/prusa:/dev/prusa
    environment:
      - ENABLE_MJPG_STREAMER=false
      - TZ=Europe/Warsaw
    ports:
      - 8082:5000
  
  artillery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: on-failure
    volumes:
      - /dev:/dev
      - /opt/op/artillery:/octoprint
      - /opt/op/plugins:/octoprint/vendor
    devices:
      - /dev/artillery:/dev/artillery
    environment:
      - ENABLE_MJPG_STREAMER=false
      - TZ=Europe/Warsaw
    ports:
      - 8081:5000

  mariner:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: on-failure
    volumes:
      - /dev:/dev
      - /opt/op/mariner:/octoprint
    devices:
      - /dev/ttyACM2:/dev/tty/ACM2
    environment:
      - ENABLE_MJPG_STREAMER=false
      - TZ=Europe/Warsaw
    ports:
      - 8084:5000

